---
- name: Deploy Echo Service
  hosts: debian_vms
  become: yes
  tasks:
    - name: Update APT package repository cache
      apt:
        update_cache: yes

    - name: Install Python3, pip, and venv
      apt:
        name: 
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Create a directory for the echo service
      file:
        path: /opt/echo_service
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create a Python virtual environment
      command: python3 -m venv /opt/echo_service/venv
      args:
        creates: /opt/echo_service/venv/bin/activate

    - name: Install Flask in the virtual environment
      command: /opt/echo_service/venv/bin/pip install flask

    - name: Create echo service script
      copy:
        dest: /opt/echo_service/app.py
        content: |
          from flask import Flask, request, jsonify
          app = Flask(__name__)

          @app.route('/', methods=['GET'])
          def echo():
              message = request.args.get('message', 'Hello, World!')
              return jsonify({'message': message})

          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=5001)

    - name: Create systemd service file for echo service
      copy:
        dest: /etc/systemd/system/echo_service.service
        content: |
          [Unit]
          Description=Echo Service
          After=network.target

          [Service]
          User={{ ansible_user }}
          WorkingDirectory=/opt/echo_service
          ExecStart=/opt/echo_service/venv/bin/python /opt/echo_service/app.py

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to pick up new service file
      command: systemctl daemon-reload

    - name: Start and enable echo service
      systemd:
        name: echo_service
        enabled: yes
        state: started

